### PR TITLE
adding assertion that SDM exists

### PR DESCRIPTION
**Pull request by caseyjlaw**
Also bumped version number so I pypi knows which version is the latest

### CODE REVIEW

**Comment by caseyjlaw** [comment]
This is still confusing because of the way we are merging forks, but basically I've added some tests. I also integrated with travis-ci for automated testing of my fork at https://travis-ci.org/realfastvla/sdmpy.
My hope is to slowly make it easier to use Python 3.6. Not sure we can get there, but tests help everyone.

**Comment by demorest** [comment]
Ok, thanks Casey, adding tests and travis-ci is a great idea!  I'm not really happy with how we've handled the different branches/merging/etc.  I think it's made the commit history kind of a mess.  What I would prefer is for this to be the main/standard branch; OK to do development in the realfast fork, but pull requests should be sent back to this branch when new stuff is added (rather than the other way around).  Let me take a look through this and see if there is anything we can do to fix this up now before merging this stuff in..

**Comment by caseyjlaw** [comment]
BTW, I've pushed this python 2/3 compatible version to pypi, so now we can recommend people `pip install sdmpy`.
More tests would be nice, but basic tests here (and within rfpipe) suggest thing are working well after the python 2/3 changes.

**Comment by demorest** [comment]
Thanks for all this Casey.  I'm going to attempt to fix up the git mess this afternoon.. do you have any other changes in the works?  If they are related to this development might be good to get them in here, otherwise maybe hold off until things are straightened out then put in a new PR.

**Comment by caseyjlaw** [comment]
I just pushed my latest commit. Should all be Python 2/3 compatible and passing (simple) tests.

**Comment by demorest** [comment]
Ok, I am going to rebase all your changes onto my branch, push this into realfastvla/master, then merge this pull request.  I've been testing this out locally, it gets rid of all the extraneous merge/PR commits, and should bring this branch and the realfast one into sync with each other.  I'll back up the current realfastvla/master into a separate branch just in case of problems.. sound good?

PS, please don't commit anything else to the realfast branch until I'm done with this.. thanks!

**Comment by caseyjlaw** [comment]
Go for it.

**Comment by demorest** [comment]
Hm, looks like I don't have permissions to commit directly to realfastvla/sdmpy.  Could you add me to that project?

**Comment by caseyjlaw** [comment]
ok, you are admin now.

**Comment by demorest** [comment]
I'm still getting permission denied when I try to push stuff .. ?

**Comment by caseyjlaw** [comment]
Sorry, I added you to the wrong repo! Now you should be admin of
realfastvla/sdmpy

**Comment by demorest** [comment]
Ok, thanks ;)

I think this is all done now.  The two branches are even and tests still are passing.  If you have local clones of the realfastvla/sdmpy repo you probably should just delete them and replace with a fresh checkout.  Doing a `git pull` into these seems to cause weird duplicated history entries, and will probably lead to problems down the line.  Let me know if you see any issues with any of this!

**Comment by caseyjlaw** [comment]
Ok, I've started fresh with a new clone. Looking good!

**Pull request merged**
